#数据库连接
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: hn123456Aa
mybatis:
  # 实体类路径
  type-aliases-package: com.boba.springbootmybatis.entity
  # mapper.xml路径
  mapper-locations: classpath:mapper/*.xml